---
# tasks file for install_exa
- name: Install via package manager (Linux as root)
  when: use_root == true
  become: true
  become_user: root
  package:
    name:
      - exa
    state: present
- name: Install exa as local user (Linux)
  when: use_root != true and ansible_facts['os_family'] != "Darwin"
  unarchive:
    creates: "${HOME}/.local/bin/exa"
    src: https://github.com/ogham/exa/releases/download/v0.10.0/exa-linux-x86_64-v0.10.0.zip
    dest: ${HOME}/.local/
    remote_src: true

- name: Install exa as local user (Darwin)
  when: use_root != true and ansible_facts['os_family'] == "Darwin"
  shell:
    creates: "${HOME}/.local/bin/exa"
    cmd: |
      mkdir -p exa
      cd exa
      wget https://github.com/ogham/exa/releases/download/v0.10.0/exa-macos-x86_64-v0.10.0.zip
      tar xvzf exa-macos-x86_64-v0.10.0.zip
      mkdir -p ${HOME}/.local/bin
      mkdir -p ${HOME}/.local/man
      mv exa-macos-x86_64-v0.10.0/bin/exa ${HOME}/.local/bin
      mv exa-macos-x86_64-v0.10.0/man/* ${HOME}/.local/man
      cd ..
      rm -rf exa
