---
# tasks file for install_lunarvim
- name: Install lvim
  shell:
    creates: ${HOME}/.local/bin/lvim
    cmd: |
      export RUSTUP_HOME="${XDG_DATA_HOME:=${HOME}/.local/share}"/rustup
      export CARGO_HOME="${XDG_DATA_HOME:=${HOME}/.local/share}"/cargo
      export PATH=${PATH}:${CARGO_HOME}/bin
      export LV_BRANCH='release-1.2/neovim-0.8'
      curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh > lvim_install.sh
      chmod u+x lvim_install.sh
      ./lvim_install.sh --yes --install-dependencies
      rm ./lvim_install.sh
