#!/usr/bin/env python3

import sys

def main():
    print(f"This is a Python program {sys.executable} which runs after every push in YADM")

if __name__ == "__main__":
    main()

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4 syntax=python
