---
- name: Install pass as local user (Linux)
  when: use_root != true
  shell:
    creates: ${HOME}/.local/bin/pass
    cmd: |
      wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.4.tar.xz
      tar xvf password-store-1.7.4.tar.xz
      export PREFIX=${HOME}/.local
      cd password-store-1.7.4
      make install
      cd ..
      rm -rf password-store-1.7.4*
- name: Install via package manager (Linux as root)
  when: use_root == true
  become: true
  become_user: root
  package:
    name:
      - pass
    state: present
