---
# tasks file for install_bat
- name: Install via package manager (Linux as root)
  when: use_root == true
  become: true
  become_user: root
  package:
    name:
      - bat
    state: present
- name: Install bat as local user (Linux)
  when: use_root != true and ansible_facts['os_family'] != "Darwin"
  shell:
    creates: "${HOME}/.local/bin/bat"
    cmd: |
      wget https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz 
      tar xvzf bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz
      mkdir -p ${HOME}/.local/bin
      mkdir -p ${HOME}/.local/man
      mv bat-v0.22.1-x86_64-unknown-linux-gnu/bat ${HOME}/.local/bin
      mv bat-v0.22.1-x86_64-unknown-linux-gnu/bat.1 ${HOME}/.local/man
      rm -r bat-v0.22.1-x86_64-unknown-linux-gnu bat-v0.22.1-x86_64-unknown-linux-gnu.tar.gz
