# Tests if the ansible playbooks can deploy properly by faking a Ubuntu VM via vagrant.

name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('.config/dots-ci/Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Install Ansible
        run: brew install ansible

      - name: Run vagrant up
        run: |
          export VAGRANT_VAGRANTFILE=.config/dots-ci/Vagrantfile
          export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:=${HOME}/.config}/ansible/ansible.cfg"
          export ANSIBLE_HOME="${XDG_CONFIG_HOME:=${HOME}/.config}/ansible"
          vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"
